VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Iloaders"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Function loadCustomers() As Collection

End Function

Public Function loadWorks() As Collection

End Function

Public Function getNewNumber() As Integer

End Function

