VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IWork"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Property Get workName() As String

End Property
Public Property Get partName() As String

End Property

Public Property Get workPrice() As Double

End Property

Public Property Get partPrice() As Double

End Property


